#
# Feiyi zshrc customization
#


# Path to your oh-my-zsh installation.

export ZSH="$HOME/.oh-my-zsh"

# show conda env if not empty
function conda_prompt_info() {
  [[ -z "$CONDA_DEFAULT_ENV" ]] && return 0
  echo "($CONDA_DEFAULT_ENV)"  
}

# platform specific settings
case `uname` in
  Darwin)
    # commands for OS X go here
  ;;
  Linux)
    # commands for Linux go here
  ;;
  FreeBSD)
    # commands for FreeBSD go here
  ;;
esac

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="avit"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in ~/.oh-my-zsh/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to automatically update without prompting.
# DISABLE_UPDATE_PROMPT="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS=true

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi


export LSCOLORS="Dxfxcxdxbxegedabagacad"



# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#

alias ls='ls -F'
alias rm='rm -i'

# ORNL alias
alias bsub1="bsub -W 24:00 -nnodes 1 -q storage -P STF006Accept -Is /bin/bash"
alias summit="ssh -X -I /usr/local/lib/opensc-pkcs11.so fwang2@summit.olcf.ornl.gov"
alias summitsftp='sftp -o SmartcardDevice=/usr/local/lib/opensc-pkcs11.so fwang2@summit.olcf.ornl.gov'
alias peak="ssh -X peak.olcf.ornl.gov"
alias summitdev="ssh -X summitdev"
alias summit="ssh -X summit"
alias summit_load="module load gcc boost"
alias summit_unload="module unload gcc boost"
alias summit_debug1="bsub -P STF008 -nnodes 1 -W 60 -alloc_flags gpumps -Is $SHELL"
alias summit_debug2="bsub -P STF008 -nnodes 2 -W 60 -alloc_flags gpumps -Is $SHELL"
alias pie="ssh -X f7b@pie" 
alias lfs-mgmt1="ssh fwang2@lfs-mgmt1.ccs.ornl.gov"
alias aicip="ssh f7b@aicip.eecs.utk.edu"
alias panda="ssh f7b@panda.eecs.utk.edu"
alias login1="ssh f7b@login1.ornl.gov"
alias ccshome="ssh -I /usr/local/lib/opensc-pkcs11.so fwang2@home.ccs.ornl.gov"
alias hub="ssh -X -I /usr/local/lib/opensc-pkcs11.so fwang2@hub.ccs.ornl.gov"
alias hubsftp="sftp -o "SmartcardDevice=/usr/local/lib/opensc-pkcs11.so" fwang2@hub.ccs.ornl.gov"
alias testbed-mgmt1="ssh fwang2@testbed-mgmt1"
alias pike-mgmt1="ssh fwang2@pike-mgmt1"

# need to go into cave first
alias lustre-mgmt1="ssh fwang2@lustre-mgmt1"
alias sudo-mgmt="sudo /opt/eas/bin/eash"

##  TMUX

alias tm="tmux attach || tmux new"
alias tmux-k="tmux kill-session"
alias tmux-ls="tmux ls"
alias tmux-a="tmux attach-session -d"
alias tmux-n="tmux new-session"

# -------------------------------------------
#            GNU global
# -------------------------------------------
#
# -a make alphabetical index
# -D generate tag list dynamically
# -F use frame for top page
# -f add search form using CGI
# -g execute gtags before starting job
# -h insert function header?
# -I use Icon?
# -n line number
# -o other files in addtion to source file
# -s make archor for symbols as well
# -T use table tag for file index
#
alias gencalls="find . -name *.[ch] | xargs cflow --tree --format=posix > cflow.out"
alias gentags="gencalls; htags -agnosT -fF --fixed-guide --auto-completion --tree-view=filetree --call-tree cflow.out"

# -------------------------------------------
#            Git alias
# -------------------------------------------

alias git_reset='git reset --hard ORIG_HEAD'
alias git_merge_devel='git merge --no-commit --no-ff devel'
alias git-list-authors='git log --all --pretty="format:%an <%aE>" | sort -u'

# -------------------------------------------
#            Docker
# -------------------------------------------

alias docker-container-stop='docker container stop $(docker container ls -q)'
alias docker-container-wipe='docker container rm $(docker container ls -q)'
alias docker-image-wipe='docker image rm $(docker image ls -q) -f'


# -------------------------------------------
#            zshrc
# -------------------------------------------

# %m hostname up to the first dot
# %* display 24 hr time format
PROMPT='
$USER@%M $(conda_prompt_info) ${_current_dir} $(git_prompt_info) $(ruby_prompt_info)
%{%(!.%F{red}.%F{white})%}%{$fg_bold[white]%}%* ▶%{$resetcolor%} '

# current directory path customization
# change from default blue to yellow
typeset +H _current_dir="%{$fg_bold[yellow]%}%3~%{$reset_color%} "


export GOPATH="$HOME/go"
export PATH="$HOME/sys/bin:$HOME/go/bin:/home/linuxbrew/.linuxbrew/bin:$PATH"

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/opt/anaconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    # this is where we run on Mac
    eval "$__conda_setup"
else
    if [ -f "/opt/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/opt/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/opt/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

